package com.swozo.api.common.files.storage;

import com.swozo.api.common.files.request.StorageAccessRequest;
import org.springframework.scheduling.annotation.Async;

public interface StorageProvider {
    void setupRequirements();

    StorageAccessRequest createAuthorizedUploadRequest(String storageObjectName, long maxFileSizeBytes);

    StorageAccessRequest createAuthorizedDownloadRequest(String storageObjectName);

    /**
     * Checks if provided storageAccessRequest was indeed generated by this provider
     */
    boolean isValid(StorageAccessRequest storageAccessRequest);

    StorageProviderType getProviderType();

    @Async
    void cleanup(String storageObjectName);
}
