package com.swozo.api.common.files.storage;

import com.swozo.config.CloudProvider;
import com.swozo.utils.StorageAccessRequest;
import org.springframework.scheduling.annotation.Async;

import java.time.Duration;
import java.util.concurrent.CompletableFuture;

public interface StorageProvider {
    StorageAccessRequest createAuthorizedUploadRequest(
            String bucketName, String storageObjectName, long maxFileSizeBytes, Duration validity);

    StorageAccessRequest createAuthorizedDownloadRequest(String bucketName, String storageObjectName, Duration validity);

    /**
     * Checks if provided StorageAccessRequest was indeed generated by this provider
     */
    boolean isValid(StorageAccessRequest storageAccessRequest);

    CloudProvider getProviderType();

    @Async
    CompletableFuture<Void> cleanup(String bucketName, String storageObjectName);
}
