package com.swozo.api.common.files.storage;

import com.swozo.api.common.files.request.StorageAccessRequest;
import com.swozo.config.CloudProvider;
import org.springframework.scheduling.annotation.Async;

import java.util.concurrent.CompletableFuture;

public interface StorageProvider {
    StorageAccessRequest createAuthorizedUploadRequest(String storageObjectName, long maxFileSizeBytes);

    StorageAccessRequest createAuthorizedDownloadRequest(String storageObjectName);

    /**
     * Checks if provided StorageAccessRequest was indeed generated by this provider
     */
    boolean isValid(StorageAccessRequest storageAccessRequest);

    CloudProvider getProviderType();

    @Async
    CompletableFuture<Void> cleanup(String storageObjectName);
}
