# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"

  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus   = 1
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Provision with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../software/install-docker.yml"
  end

end

