package com.swozo.api.auth.dto;

import java.util.List;

// AppRole instead of string so autogenerated frontend types will be prettier
public record AuthData(String accessToken, long expiresIn, List<AppRole> roles) {
}
