FROM openjdk:8-jdk-alpine

ENV GCP_SSH_KEY_PATH auth/orchestrator_id_rsa
ENV GOOGLE_APPLICATION_CREDENTIALS auth/orchestrator-key.json
ENV JUPYTER_PLAYBOOK_PATH=playbook/software/jupyter/prepare-and-run-jupyter.yml

ENTRYPOINT ["java","-jar","/app.jar"]