version: '3.7'

services:
  swozo-orchestrator:
    image: swozo/orchestrator:latest
    ports:
      - "8080:8080"
    environment:
      GCP_PROJECT: <placeholder>
      GCP_ZONE: <placeholder>
      GCP_SSH_USER: <placeholder>
