/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AuthData,
    AuthDataFromJSON,
    AuthDataToJSON,
    LoginData,
    LoginDataFromJSON,
    LoginDataToJSON,
} from '../models';

export interface LoginRequest {
    loginData: LoginData;
}

/**
 * 
 */
export class AuthControllerApi extends runtime.BaseAPI {

    /**
     * Login user
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AuthData>> {
        if (requestParameters.loginData === null || requestParameters.loginData === undefined) {
            throw new runtime.RequiredError('loginData','Required parameter requestParameters.loginData was null or undefined when calling login.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginDataToJSON(requestParameters.loginData),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthDataFromJSON(jsonValue));
    }

    /**
     * Login user
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit): Promise<AuthData> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
