/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Activity,
    ActivityFromJSON,
    ActivityToJSON,
    AddStudentRequest,
    AddStudentRequestFromJSON,
    AddStudentRequestToJSON,
    Course,
    CourseFromJSON,
    CourseToJSON,
    CourseDetailsDto,
    CourseDetailsDtoFromJSON,
    CourseDetailsDtoToJSON,
    CreateCourseRequest,
    CreateCourseRequestFromJSON,
    CreateCourseRequestToJSON,
    User,
    UserFromJSON,
    UserToJSON,
} from '../models';

export interface AddCourseRequest {
    createCourseRequest: CreateCourseRequest;
}

export interface AddStudentToCourseRequest {
    courseId: number;
    addStudentRequest: AddStudentRequest;
}

export interface DeleteCourseRequest {
    id: number;
}

export interface EditCourseRequest {
    id: number;
    createCourseRequest: CreateCourseRequest;
}

export interface GetCourseRequest {
    id: number;
}

export interface GetCourseActivityListRequest {
    id: number;
}

export interface RemoveStudentFromCourseRequest {
    courseId: number;
    user: User;
}

/**
 * 
 */
export class CourseControllerApi extends runtime.BaseAPI {

    /**
     */
    async addCourseRaw(requestParameters: AddCourseRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CourseDetailsDto>> {
        if (requestParameters.createCourseRequest === null || requestParameters.createCourseRequest === undefined) {
            throw new runtime.RequiredError('createCourseRequest','Required parameter requestParameters.createCourseRequest was null or undefined when calling addCourse.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT_AUTH", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/courses`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCourseRequestToJSON(requestParameters.createCourseRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseDetailsDtoFromJSON(jsonValue));
    }

    /**
     */
    async addCourse(requestParameters: AddCourseRequest, initOverrides?: RequestInit): Promise<CourseDetailsDto> {
        const response = await this.addCourseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async addStudentToCourseRaw(requestParameters: AddStudentToCourseRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CourseDetailsDto>> {
        if (requestParameters.courseId === null || requestParameters.courseId === undefined) {
            throw new runtime.RequiredError('courseId','Required parameter requestParameters.courseId was null or undefined when calling addStudentToCourse.');
        }

        if (requestParameters.addStudentRequest === null || requestParameters.addStudentRequest === undefined) {
            throw new runtime.RequiredError('addStudentRequest','Required parameter requestParameters.addStudentRequest was null or undefined when calling addStudentToCourse.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT_AUTH", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/courses/{courseId}/students`.replace(`{${"courseId"}}`, encodeURIComponent(String(requestParameters.courseId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddStudentRequestToJSON(requestParameters.addStudentRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseDetailsDtoFromJSON(jsonValue));
    }

    /**
     */
    async addStudentToCourse(requestParameters: AddStudentToCourseRequest, initOverrides?: RequestInit): Promise<CourseDetailsDto> {
        const response = await this.addStudentToCourseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteCourseRaw(requestParameters: DeleteCourseRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteCourse.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT_AUTH", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/courses/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteCourse(requestParameters: DeleteCourseRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteCourseRaw(requestParameters, initOverrides);
    }

    /**
     */
    async editCourseRaw(requestParameters: EditCourseRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Course>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling editCourse.');
        }

        if (requestParameters.createCourseRequest === null || requestParameters.createCourseRequest === undefined) {
            throw new runtime.RequiredError('createCourseRequest','Required parameter requestParameters.createCourseRequest was null or undefined when calling editCourse.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT_AUTH", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/courses/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCourseRequestToJSON(requestParameters.createCourseRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseFromJSON(jsonValue));
    }

    /**
     */
    async editCourse(requestParameters: EditCourseRequest, initOverrides?: RequestInit): Promise<Course> {
        const response = await this.editCourseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCourseRaw(requestParameters: GetCourseRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CourseDetailsDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getCourse.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT_AUTH", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/courses/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseDetailsDtoFromJSON(jsonValue));
    }

    /**
     */
    async getCourse(requestParameters: GetCourseRequest, initOverrides?: RequestInit): Promise<CourseDetailsDto> {
        const response = await this.getCourseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getCourseActivityListRaw(requestParameters: GetCourseActivityListRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Activity>>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getCourseActivityList.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT_AUTH", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/courses/{id}/activities`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ActivityFromJSON));
    }

    /**
     */
    async getCourseActivityList(requestParameters: GetCourseActivityListRequest, initOverrides?: RequestInit): Promise<Array<Activity>> {
        const response = await this.getCourseActivityListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getUserCoursesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<CourseDetailsDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT_AUTH", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/courses`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CourseDetailsDtoFromJSON));
    }

    /**
     */
    async getUserCourses(initOverrides?: RequestInit): Promise<Array<CourseDetailsDto>> {
        const response = await this.getUserCoursesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async removeStudentFromCourseRaw(requestParameters: RemoveStudentFromCourseRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CourseDetailsDto>> {
        if (requestParameters.courseId === null || requestParameters.courseId === undefined) {
            throw new runtime.RequiredError('courseId','Required parameter requestParameters.courseId was null or undefined when calling removeStudentFromCourse.');
        }

        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user','Required parameter requestParameters.user was null or undefined when calling removeStudentFromCourse.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT_AUTH", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/courses/{courseId}/students`.replace(`{${"courseId"}}`, encodeURIComponent(String(requestParameters.courseId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: UserToJSON(requestParameters.user),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseDetailsDtoFromJSON(jsonValue));
    }

    /**
     */
    async removeStudentFromCourse(requestParameters: RemoveStudentFromCourseRequest, initOverrides?: RequestInit): Promise<CourseDetailsDto> {
        const response = await this.removeStudentFromCourseRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
