/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ServiceModule,
    ServiceModuleFromJSON,
    ServiceModuleToJSON,
} from '../models';

export interface GetServiceModuleRequest {
    id: number;
}

export interface UpdateServiceModuleRequest {
    moduleId: number;
    serviceModule: ServiceModule;
}

/**
 * 
 */
export class ServiceModuleControllerApi extends runtime.BaseAPI {

    /**
     */
    async getModuleListRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ServiceModule>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT_AUTH", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/service-modules`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceModuleFromJSON));
    }

    /**
     */
    async getModuleList(initOverrides?: RequestInit): Promise<Array<ServiceModule>> {
        const response = await this.getModuleListRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getServiceModuleRaw(requestParameters: GetServiceModuleRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ServiceModule>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getServiceModule.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT_AUTH", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/service-modules/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceModuleFromJSON(jsonValue));
    }

    /**
     */
    async getServiceModule(requestParameters: GetServiceModuleRequest, initOverrides?: RequestInit): Promise<ServiceModule> {
        const response = await this.getServiceModuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateServiceModuleRaw(requestParameters: UpdateServiceModuleRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ServiceModule>> {
        if (requestParameters.moduleId === null || requestParameters.moduleId === undefined) {
            throw new runtime.RequiredError('moduleId','Required parameter requestParameters.moduleId was null or undefined when calling updateServiceModule.');
        }

        if (requestParameters.serviceModule === null || requestParameters.serviceModule === undefined) {
            throw new runtime.RequiredError('serviceModule','Required parameter requestParameters.serviceModule was null or undefined when calling updateServiceModule.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT_AUTH", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/service-modules/{moduleId}`.replace(`{${"moduleId"}}`, encodeURIComponent(String(requestParameters.moduleId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceModuleToJSON(requestParameters.serviceModule),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceModuleFromJSON(jsonValue));
    }

    /**
     */
    async updateServiceModule(requestParameters: UpdateServiceModuleRequest, initOverrides?: RequestInit): Promise<ServiceModule> {
        const response = await this.updateServiceModuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
