/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Activity,
    ActivityFromJSON,
    ActivityFromJSONTyped,
    ActivityToJSON,
} from './Activity';
import {
    ActivityLink,
    ActivityLinkFromJSON,
    ActivityLinkFromJSONTyped,
    ActivityLinkToJSON,
} from './ActivityLink';
import {
    ServiceModule,
    ServiceModuleFromJSON,
    ServiceModuleFromJSONTyped,
    ServiceModuleToJSON,
} from './ServiceModule';

/**
 * 
 * @export
 * @interface ActivityModule
 */
export interface ActivityModule {
    /**
     * 
     * @type {number}
     * @memberof ActivityModule
     */
    id?: number;
    /**
     * 
     * @type {ServiceModule}
     * @memberof ActivityModule
     */
    module?: ServiceModule;
    /**
     * 
     * @type {Activity}
     * @memberof ActivityModule
     */
    activity?: Activity;
    /**
     * 
     * @type {string}
     * @memberof ActivityModule
     */
    instruction?: string;
    /**
     * 
     * @type {Array<ActivityLink>}
     * @memberof ActivityModule
     */
    links?: Array<ActivityLink>;
}

export function ActivityModuleFromJSON(json: any): ActivityModule {
    return ActivityModuleFromJSONTyped(json, false);
}

export function ActivityModuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityModule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'module': !exists(json, 'module') ? undefined : ServiceModuleFromJSON(json['module']),
        'activity': !exists(json, 'activity') ? undefined : ActivityFromJSON(json['activity']),
        'instruction': !exists(json, 'instruction') ? undefined : json['instruction'],
        'links': !exists(json, 'links') ? undefined : ((json['links'] as Array<any>).map(ActivityLinkFromJSON)),
    };
}

export function ActivityModuleToJSON(value?: ActivityModule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'module': ServiceModuleToJSON(value.module),
        'activity': ActivityToJSON(value.activity),
        'instruction': value.instruction,
        'links': value.links === undefined ? undefined : ((value.links as Array<any>).map(ActivityLinkToJSON)),
    };
}

