/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ActivityInstruction,
    ActivityInstructionFromJSON,
    ActivityInstructionFromJSONTyped,
    ActivityInstructionToJSON,
} from './ActivityInstruction';

/**
 * 
 * @export
 * @interface ActivityDetailsReq
 */
export interface ActivityDetailsReq {
    /**
     * 
     * @type {string}
     * @memberof ActivityDetailsReq
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityDetailsReq
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof ActivityDetailsReq
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof ActivityDetailsReq
     */
    endTime: Date;
    /**
     * 
     * @type {Array<ActivityInstruction>}
     * @memberof ActivityDetailsReq
     */
    instructionsFromTeacher: Array<ActivityInstruction>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ActivityDetailsReq
     */
    selectedModulesIds: Array<number>;
}

export function ActivityDetailsReqFromJSON(json: any): ActivityDetailsReq {
    return ActivityDetailsReqFromJSONTyped(json, false);
}

export function ActivityDetailsReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityDetailsReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
        'instructionsFromTeacher': ((json['instructionsFromTeacher'] as Array<any>).map(ActivityInstructionFromJSON)),
        'selectedModulesIds': json['selectedModulesIds'],
    };
}

export function ActivityDetailsReqToJSON(value?: ActivityDetailsReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'startTime': (value.startTime.toISOString()),
        'endTime': (value.endTime.toISOString()),
        'instructionsFromTeacher': ((value.instructionsFromTeacher as Array<any>).map(ActivityInstructionToJSON)),
        'selectedModulesIds': value.selectedModulesIds,
    };
}

