/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ServiceConnectionDetailsDto,
    ServiceConnectionDetailsDtoFromJSON,
    ServiceConnectionDetailsDtoFromJSONTyped,
    ServiceConnectionDetailsDtoToJSON,
} from './ServiceConnectionDetailsDto';
import {
    ServiceModuleDetailsDto,
    ServiceModuleDetailsDtoFromJSON,
    ServiceModuleDetailsDtoFromJSONTyped,
    ServiceModuleDetailsDtoToJSON,
} from './ServiceModuleDetailsDto';

/**
 * 
 * @export
 * @interface ActivityModuleDetailsDto
 */
export interface ActivityModuleDetailsDto {
    /**
     * 
     * @type {number}
     * @memberof ActivityModuleDetailsDto
     */
    id: number;
    /**
     * 
     * @type {ServiceModuleDetailsDto}
     * @memberof ActivityModuleDetailsDto
     */
    module: ServiceModuleDetailsDto;
    /**
     * 
     * @type {string}
     * @memberof ActivityModuleDetailsDto
     */
    instruction: string;
    /**
     * 
     * @type {Array<ServiceConnectionDetailsDto>}
     * @memberof ActivityModuleDetailsDto
     */
    connectionDetails: Array<ServiceConnectionDetailsDto>;
}

export function ActivityModuleDetailsDtoFromJSON(json: any): ActivityModuleDetailsDto {
    return ActivityModuleDetailsDtoFromJSONTyped(json, false);
}

export function ActivityModuleDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityModuleDetailsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'module': ServiceModuleDetailsDtoFromJSON(json['module']),
        'instruction': json['instruction'],
        'connectionDetails': ((json['connectionDetails'] as Array<any>).map(ServiceConnectionDetailsDtoFromJSON)),
    };
}

export function ActivityModuleDetailsDtoToJSON(value?: ActivityModuleDetailsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'module': ServiceModuleDetailsDtoToJSON(value.module),
        'instruction': value.instruction,
        'connectionDetails': ((value.connectionDetails as Array<any>).map(ServiceConnectionDetailsDtoToJSON)),
    };
}

