/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityInstructionData
 */
export interface ActivityInstructionData {
    /**
     * 
     * @type {string}
     * @memberof ActivityInstructionData
     */
    header?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityInstructionData
     */
    body: string;
}

export function ActivityInstructionDataFromJSON(json: any): ActivityInstructionData {
    return ActivityInstructionDataFromJSONTyped(json, false);
}

export function ActivityInstructionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityInstructionData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': !exists(json, 'header') ? undefined : json['header'],
        'body': json['body'],
    };
}

export function ActivityInstructionDataToJSON(value?: ActivityInstructionData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': value.header,
        'body': value.body,
    };
}

