/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ActivityInstruction,
    ActivityInstructionFromJSON,
    ActivityInstructionFromJSONTyped,
    ActivityInstructionToJSON,
} from './ActivityInstruction';
import {
    ActivityLinkInfo,
    ActivityLinkInfoFromJSON,
    ActivityLinkInfoFromJSONTyped,
    ActivityLinkInfoToJSON,
} from './ActivityLinkInfo';

/**
 * 
 * @export
 * @interface ActivityDetailsResp
 */
export interface ActivityDetailsResp {
    /**
     * 
     * @type {number}
     * @memberof ActivityDetailsResp
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityDetailsResp
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityDetailsResp
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof ActivityDetailsResp
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof ActivityDetailsResp
     */
    endTime: Date;
    /**
     * 
     * @type {Array<ActivityInstruction>}
     * @memberof ActivityDetailsResp
     */
    instructionsFromTeacher: Array<ActivityInstruction>;
    /**
     * 
     * @type {Array<ActivityLinkInfo>}
     * @memberof ActivityDetailsResp
     */
    activityLinkInfos: Array<ActivityLinkInfo>;
}

export function ActivityDetailsRespFromJSON(json: any): ActivityDetailsResp {
    return ActivityDetailsRespFromJSONTyped(json, false);
}

export function ActivityDetailsRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityDetailsResp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
        'instructionsFromTeacher': ((json['instructionsFromTeacher'] as Array<any>).map(ActivityInstructionFromJSON)),
        'activityLinkInfos': ((json['activityLinkInfos'] as Array<any>).map(ActivityLinkInfoFromJSON)),
    };
}

export function ActivityDetailsRespToJSON(value?: ActivityDetailsResp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'startTime': (value.startTime.toISOString()),
        'endTime': (value.endTime.toISOString()),
        'instructionsFromTeacher': ((value.instructionsFromTeacher as Array<any>).map(ActivityInstructionToJSON)),
        'activityLinkInfos': ((value.activityLinkInfos as Array<any>).map(ActivityLinkInfoToJSON)),
    };
}

