/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ActivityInstruction,
    ActivityInstructionFromJSON,
    ActivityInstructionFromJSONTyped,
    ActivityInstructionToJSON,
} from './ActivityInstruction';
import {
    ActivityModule,
    ActivityModuleFromJSON,
    ActivityModuleFromJSONTyped,
    ActivityModuleToJSON,
} from './ActivityModule';
import {
    RemoteFile,
    RemoteFileFromJSON,
    RemoteFileFromJSONTyped,
    RemoteFileToJSON,
} from './RemoteFile';

/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof Activity
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Activity
     */
    endTime?: Date;
    /**
     * 
     * @type {Array<ActivityInstruction>}
     * @memberof Activity
     */
    instructionsFromTeacher?: Array<ActivityInstruction>;
    /**
     * 
     * @type {Array<ActivityModule>}
     * @memberof Activity
     */
    modules?: Array<ActivityModule>;
    /**
     * 
     * @type {Array<RemoteFile>}
     * @memberof Activity
     */
    publicFiles?: Array<RemoteFile>;
    /**
     * 
     * @type {number}
     * @memberof Activity
     */
    course?: number;
}

export function ActivityFromJSON(json: any): Activity {
    return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'startTime': !exists(json, 'startTime') ? undefined : (new Date(json['startTime'])),
        'endTime': !exists(json, 'endTime') ? undefined : (new Date(json['endTime'])),
        'instructionsFromTeacher': !exists(json, 'instructionsFromTeacher') ? undefined : ((json['instructionsFromTeacher'] as Array<any>).map(ActivityInstructionFromJSON)),
        'modules': !exists(json, 'modules') ? undefined : ((json['modules'] as Array<any>).map(ActivityModuleFromJSON)),
        'publicFiles': !exists(json, 'publicFiles') ? undefined : ((json['publicFiles'] as Array<any>).map(RemoteFileFromJSON)),
        'course': !exists(json, 'course') ? undefined : json['course'],
    };
}

export function ActivityToJSON(value?: Activity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'startTime': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'endTime': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'instructionsFromTeacher': value.instructionsFromTeacher === undefined ? undefined : ((value.instructionsFromTeacher as Array<any>).map(ActivityInstructionToJSON)),
        'modules': value.modules === undefined ? undefined : ((value.modules as Array<any>).map(ActivityModuleToJSON)),
        'publicFiles': value.publicFiles === undefined ? undefined : ((value.publicFiles as Array<any>).map(RemoteFileToJSON)),
        'course': value.course,
    };
}

