/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ServiceConnectionDetailsDto,
    ServiceConnectionDetailsDtoFromJSON,
    ServiceConnectionDetailsDtoFromJSONTyped,
    ServiceConnectionDetailsDtoToJSON,
} from './ServiceConnectionDetailsDto';
import {
    ServiceModuleSummaryDto,
    ServiceModuleSummaryDtoFromJSON,
    ServiceModuleSummaryDtoFromJSONTyped,
    ServiceModuleSummaryDtoToJSON,
} from './ServiceModuleSummaryDto';

/**
 * 
 * @export
 * @interface ActivityModuleDetailsDto
 */
export interface ActivityModuleDetailsDto {
    /**
     * 
     * @type {number}
     * @memberof ActivityModuleDetailsDto
     */
    id: number;
    /**
     * 
     * @type {ServiceModuleSummaryDto}
     * @memberof ActivityModuleDetailsDto
     */
    serviceModule: ServiceModuleSummaryDto;
    /**
     * 
     * @type {Array<ServiceConnectionDetailsDto>}
     * @memberof ActivityModuleDetailsDto
     */
    connectionDetails: Array<ServiceConnectionDetailsDto>;
}

export function ActivityModuleDetailsDtoFromJSON(json: any): ActivityModuleDetailsDto {
    return ActivityModuleDetailsDtoFromJSONTyped(json, false);
}

export function ActivityModuleDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityModuleDetailsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'serviceModule': ServiceModuleSummaryDtoFromJSON(json['serviceModule']),
        'connectionDetails': ((json['connectionDetails'] as Array<any>).map(ServiceConnectionDetailsDtoFromJSON)),
    };
}

export function ActivityModuleDetailsDtoToJSON(value?: ActivityModuleDetailsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'serviceModule': ServiceModuleSummaryDtoToJSON(value.serviceModule),
        'connectionDetails': ((value.connectionDetails as Array<any>).map(ServiceConnectionDetailsDtoToJSON)),
    };
}

