/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityInstruction
 */
export interface ActivityInstruction {
    /**
     * 
     * @type {number}
     * @memberof ActivityInstruction
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityInstruction
     */
    data?: string;
}

export function ActivityInstructionFromJSON(json: any): ActivityInstruction {
    return ActivityInstructionFromJSONTyped(json, false);
}

export function ActivityInstructionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityInstruction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function ActivityInstructionToJSON(value?: ActivityInstruction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'data': value.data,
    };
}

