/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ActivityInstructionDto,
    ActivityInstructionDtoFromJSON,
    ActivityInstructionDtoFromJSONTyped,
    ActivityInstructionDtoToJSON,
} from './ActivityInstructionDto';
import {
    ActivityModuleDetailsDto,
    ActivityModuleDetailsDtoFromJSON,
    ActivityModuleDetailsDtoFromJSONTyped,
    ActivityModuleDetailsDtoToJSON,
} from './ActivityModuleDetailsDto';

/**
 * 
 * @export
 * @interface ActivityDetailsDto
 */
export interface ActivityDetailsDto {
    /**
     * 
     * @type {number}
     * @memberof ActivityDetailsDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityDetailsDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityDetailsDto
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof ActivityDetailsDto
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof ActivityDetailsDto
     */
    endTime: Date;
    /**
     * 
     * @type {Array<ActivityInstructionDto>}
     * @memberof ActivityDetailsDto
     */
    instructionsFromTeacher: Array<ActivityInstructionDto>;
    /**
     * 
     * @type {Array<ActivityModuleDetailsDto>}
     * @memberof ActivityDetailsDto
     */
    activityModules: Array<ActivityModuleDetailsDto>;
}

export function ActivityDetailsDtoFromJSON(json: any): ActivityDetailsDto {
    return ActivityDetailsDtoFromJSONTyped(json, false);
}

export function ActivityDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityDetailsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
        'instructionsFromTeacher': ((json['instructionsFromTeacher'] as Array<any>).map(ActivityInstructionDtoFromJSON)),
        'activityModules': ((json['activityModules'] as Array<any>).map(ActivityModuleDetailsDtoFromJSON)),
    };
}

export function ActivityDetailsDtoToJSON(value?: ActivityDetailsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'startTime': (value.startTime.toISOString()),
        'endTime': (value.endTime.toISOString()),
        'instructionsFromTeacher': ((value.instructionsFromTeacher as Array<any>).map(ActivityInstructionDtoToJSON)),
        'activityModules': ((value.activityModules as Array<any>).map(ActivityModuleDetailsDtoToJSON)),
    };
}

