/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityLink
 */
export interface ActivityLink {
    /**
     * 
     * @type {number}
     * @memberof ActivityLink
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityLink
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityLink
     */
    connectionInfo?: string;
}

export function ActivityLinkFromJSON(json: any): ActivityLink {
    return ActivityLinkFromJSONTyped(json, false);
}

export function ActivityLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'connectionInfo': !exists(json, 'connectionInfo') ? undefined : json['connectionInfo'],
    };
}

export function ActivityLinkToJSON(value?: ActivityLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'url': value.url,
        'connectionInfo': value.connectionInfo,
    };
}

