/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RefreshTokenDto,
    RefreshTokenDtoFromJSON,
    RefreshTokenDtoFromJSONTyped,
    RefreshTokenDtoToJSON,
} from './RefreshTokenDto';

/**
 * 
 * @export
 * @interface AuthDetailsDto
 */
export interface AuthDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof AuthDetailsDto
     */
    accessToken: string;
    /**
     * 
     * @type {number}
     * @memberof AuthDetailsDto
     */
    expiresIn: number;
    /**
     * 
     * @type {RefreshTokenDto}
     * @memberof AuthDetailsDto
     */
    refreshTokenDto: RefreshTokenDto;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthDetailsDto
     */
    roles: Array<AuthDetailsDtoRolesEnum>;
}

/**
* @export
* @enum {string}
*/
export enum AuthDetailsDtoRolesEnum {
    Student = 'STUDENT',
    Teacher = 'TEACHER',
    TechnicalTeacher = 'TECHNICAL_TEACHER',
    Admin = 'ADMIN'
}

export function AuthDetailsDtoFromJSON(json: any): AuthDetailsDto {
    return AuthDetailsDtoFromJSONTyped(json, false);
}

export function AuthDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthDetailsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'expiresIn': json['expiresIn'],
        'refreshTokenDto': RefreshTokenDtoFromJSON(json['refreshTokenDto']),
        'roles': json['roles'],
    };
}

export function AuthDetailsDtoToJSON(value?: AuthDetailsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'expiresIn': value.expiresIn,
        'refreshTokenDto': RefreshTokenDtoToJSON(value.refreshTokenDto),
        'roles': value.roles,
    };
}

