/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthData
 */
export interface AuthData {
    /**
     * 
     * @type {string}
     * @memberof AuthData
     */
    accessToken: string;
    /**
     * 
     * @type {number}
     * @memberof AuthData
     */
    expiresIn: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthData
     */
    roles: Array<AuthDataRolesEnum>;
}

/**
* @export
* @enum {string}
*/
export enum AuthDataRolesEnum {
    Student = 'STUDENT',
    Teacher = 'TEACHER',
    TechnicalTeacher = 'TECHNICAL_TEACHER',
    Admin = 'ADMIN'
}

export function AuthDataFromJSON(json: any): AuthData {
    return AuthDataFromJSONTyped(json, false);
}

export function AuthDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'expiresIn': json['expiresIn'],
        'roles': json['roles'],
    };
}

export function AuthDataToJSON(value?: AuthData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
        'expiresIn': value.expiresIn,
        'roles': value.roles,
    };
}

