/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ActivityDetailsResp,
    ActivityDetailsRespFromJSON,
    ActivityDetailsRespFromJSONTyped,
    ActivityDetailsRespToJSON,
} from './ActivityDetailsResp';
import {
    UserDetailsResp,
    UserDetailsRespFromJSON,
    UserDetailsRespFromJSONTyped,
    UserDetailsRespToJSON,
} from './UserDetailsResp';

/**
 * 
 * @export
 * @interface CourseDetailsResp
 */
export interface CourseDetailsResp {
    /**
     * 
     * @type {number}
     * @memberof CourseDetailsResp
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CourseDetailsResp
     */
    name: string;
    /**
     * 
     * @type {UserDetailsResp}
     * @memberof CourseDetailsResp
     */
    teacher: UserDetailsResp;
    /**
     * 
     * @type {Date}
     * @memberof CourseDetailsResp
     */
    lastActivity: Date;
    /**
     * 
     * @type {string}
     * @memberof CourseDetailsResp
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof CourseDetailsResp
     */
    description: string;
    /**
     * 
     * @type {Array<UserDetailsResp>}
     * @memberof CourseDetailsResp
     */
    students: Array<UserDetailsResp>;
    /**
     * 
     * @type {Array<ActivityDetailsResp>}
     * @memberof CourseDetailsResp
     */
    activities: Array<ActivityDetailsResp>;
}

export function CourseDetailsRespFromJSON(json: any): CourseDetailsResp {
    return CourseDetailsRespFromJSONTyped(json, false);
}

export function CourseDetailsRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseDetailsResp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'teacher': UserDetailsRespFromJSON(json['teacher']),
        'lastActivity': (new Date(json['lastActivity'])),
        'subject': json['subject'],
        'description': json['description'],
        'students': ((json['students'] as Array<any>).map(UserDetailsRespFromJSON)),
        'activities': ((json['activities'] as Array<any>).map(ActivityDetailsRespFromJSON)),
    };
}

export function CourseDetailsRespToJSON(value?: CourseDetailsResp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'teacher': UserDetailsRespToJSON(value.teacher),
        'lastActivity': (value.lastActivity.toISOString()),
        'subject': value.subject,
        'description': value.description,
        'students': ((value.students as Array<any>).map(UserDetailsRespToJSON)),
        'activities': ((value.activities as Array<any>).map(ActivityDetailsRespToJSON)),
    };
}

