/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseSummaryDto
 */
export interface CourseSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof CourseSummaryDto
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof CourseSummaryDto
     */
    isPasswordProtected: boolean;
    /**
     * 
     * @type {string}
     * @memberof CourseSummaryDto
     */
    joinUUID: string;
}

export function CourseSummaryDtoFromJSON(json: any): CourseSummaryDto {
    return CourseSummaryDtoFromJSONTyped(json, false);
}

export function CourseSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseSummaryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'isPasswordProtected': json['isPasswordProtected'],
        'joinUUID': json['joinUUID'],
    };
}

export function CourseSummaryDtoToJSON(value?: CourseSummaryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'isPasswordProtected': value.isPasswordProtected,
        'joinUUID': value.joinUUID,
    };
}

