/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ActivityDetailsReq,
    ActivityDetailsReqFromJSON,
    ActivityDetailsReqFromJSONTyped,
    ActivityDetailsReqToJSON,
} from './ActivityDetailsReq';

/**
 * 
 * @export
 * @interface CourseDetailsReq
 */
export interface CourseDetailsReq {
    /**
     * 
     * @type {string}
     * @memberof CourseDetailsReq
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CourseDetailsReq
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof CourseDetailsReq
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof CourseDetailsReq
     */
    expectedStudentCount: number;
    /**
     * 
     * @type {Array<ActivityDetailsReq>}
     * @memberof CourseDetailsReq
     */
    activityDetailReqs: Array<ActivityDetailsReq>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CourseDetailsReq
     */
    studentEmails: Array<string>;
}

export function CourseDetailsReqFromJSON(json: any): CourseDetailsReq {
    return CourseDetailsReqFromJSONTyped(json, false);
}

export function CourseDetailsReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseDetailsReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'subject': json['subject'],
        'description': json['description'],
        'expectedStudentCount': json['expectedStudentCount'],
        'activityDetailReqs': ((json['activityDetailReqs'] as Array<any>).map(ActivityDetailsReqFromJSON)),
        'studentEmails': json['studentEmails'],
    };
}

export function CourseDetailsReqToJSON(value?: CourseDetailsReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'subject': value.subject,
        'description': value.description,
        'expectedStudentCount': value.expectedStudentCount,
        'activityDetailReqs': ((value.activityDetailReqs as Array<any>).map(ActivityDetailsReqToJSON)),
        'studentEmails': value.studentEmails,
    };
}

