/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateActivityRequest,
    CreateActivityRequestFromJSON,
    CreateActivityRequestFromJSONTyped,
    CreateActivityRequestToJSON,
} from './CreateActivityRequest';

/**
 * 
 * @export
 * @interface CreateCourseRequest
 */
export interface CreateCourseRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCourseRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseRequest
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseRequest
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCourseRequest
     */
    expectedStudentCount: number;
    /**
     * 
     * @type {Array<CreateActivityRequest>}
     * @memberof CreateCourseRequest
     */
    activities: Array<CreateActivityRequest>;
}

export function CreateCourseRequestFromJSON(json: any): CreateCourseRequest {
    return CreateCourseRequestFromJSONTyped(json, false);
}

export function CreateCourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCourseRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'subject': json['subject'],
        'description': json['description'],
        'expectedStudentCount': json['expectedStudentCount'],
        'activities': ((json['activities'] as Array<any>).map(CreateActivityRequestFromJSON)),
    };
}

export function CreateCourseRequestToJSON(value?: CreateCourseRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'subject': value.subject,
        'description': value.description,
        'expectedStudentCount': value.expectedStudentCount,
        'activities': ((value.activities as Array<any>).map(CreateActivityRequestToJSON)),
    };
}

