/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InstructionDto,
    InstructionDtoFromJSON,
    InstructionDtoFromJSONTyped,
    InstructionDtoToJSON,
} from './InstructionDto';

/**
 * 
 * @export
 * @interface CreateActivityRequest
 */
export interface CreateActivityRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateActivityRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateActivityRequest
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateActivityRequest
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateActivityRequest
     */
    endTime: Date;
    /**
     * 
     * @type {InstructionDto}
     * @memberof CreateActivityRequest
     */
    instructionFromTeacher: InstructionDto;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateActivityRequest
     */
    selectedModulesIds: Array<number>;
}

export function CreateActivityRequestFromJSON(json: any): CreateActivityRequest {
    return CreateActivityRequestFromJSONTyped(json, false);
}

export function CreateActivityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateActivityRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
        'instructionFromTeacher': InstructionDtoFromJSON(json['instructionFromTeacher']),
        'selectedModulesIds': json['selectedModulesIds'],
    };
}

export function CreateActivityRequestToJSON(value?: CreateActivityRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'startTime': (value.startTime.toISOString()),
        'endTime': (value.endTime.toISOString()),
        'instructionFromTeacher': InstructionDtoToJSON(value.instructionFromTeacher),
        'selectedModulesIds': value.selectedModulesIds,
    };
}

