/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditCourseRequest
 */
export interface EditCourseRequest {
    /**
     * 
     * @type {string}
     * @memberof EditCourseRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EditCourseRequest
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof EditCourseRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EditCourseRequest
     */
    password?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditCourseRequest
     */
    isPublic?: boolean;
}

export function EditCourseRequestFromJSON(json: any): EditCourseRequest {
    return EditCourseRequestFromJSONTyped(json, false);
}

export function EditCourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditCourseRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'isPublic': !exists(json, 'isPublic') ? undefined : json['isPublic'],
    };
}

export function EditCourseRequestToJSON(value?: EditCourseRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'subject': value.subject,
        'description': value.description,
        'password': value.password,
        'isPublic': value.isPublic,
    };
}

