/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExampleModel
 */
export interface ExampleModel {
    /**
     * 
     * @type {number}
     * @memberof ExampleModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExampleModel
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ExampleModel
     */
    someBigCollection?: string;
}

export function ExampleModelFromJSON(json: any): ExampleModel {
    return ExampleModelFromJSONTyped(json, false);
}

export function ExampleModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExampleModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'someBigCollection': !exists(json, 'someBigCollection') ? undefined : json['someBigCollection'],
    };
}

export function ExampleModelToJSON(value?: ExampleModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'someBigCollection': value.someBigCollection,
    };
}

