/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FinishServiceModuleCreationRequest
 */
export interface FinishServiceModuleCreationRequest {
    /**
     * 
     * @type {number}
     * @memberof FinishServiceModuleCreationRequest
     */
    reservationId: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof FinishServiceModuleCreationRequest
     */
    echoFieldActions: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof FinishServiceModuleCreationRequest
     */
    repeatedInitialValues: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof FinishServiceModuleCreationRequest
     */
    finalDynamicFieldValues: { [key: string]: string; };
}

export function FinishServiceModuleCreationRequestFromJSON(json: any): FinishServiceModuleCreationRequest {
    return FinishServiceModuleCreationRequestFromJSONTyped(json, false);
}

export function FinishServiceModuleCreationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinishServiceModuleCreationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reservationId': json['reservationId'],
        'echoFieldActions': json['echoFieldActions'],
        'repeatedInitialValues': json['repeatedInitialValues'],
        'finalDynamicFieldValues': json['finalDynamicFieldValues'],
    };
}

export function FinishServiceModuleCreationRequestToJSON(value?: FinishServiceModuleCreationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reservationId': value.reservationId,
        'echoFieldActions': value.echoFieldActions,
        'repeatedInitialValues': value.repeatedInitialValues,
        'finalDynamicFieldValues': value.finalDynamicFieldValues,
    };
}

