/* tslint:disable */
/* eslint-disable */
export * from './ActivityDetailsDto';
export * from './ActivityModuleDetailsDto';
export * from './AuthDetailsDto';
export * from './CourseDetailsDto';
export * from './CourseSummaryDto';
export * from './CreateActivityRequest';
export * from './CreateCourseRequest';
export * from './DynamicFieldDto';
export * from './FileDto';
export * from './FinishServiceModuleCreationRequest';
export * from './InitFileUploadRequest';
export * from './InstructionDto';
export * from './JoinCourseRequest';
export * from './LoginRequest';
export * from './ModifyParticipantRequest';
export * from './ParameterDescription';
export * from './ParticipantDetailsDto';
export * from './ReserveServiceModuleRequest';
export * from './ServiceConfig';
export * from './ServiceConnectionDetailsDto';
export * from './ServiceModuleDetailsDto';
export * from './ServiceModuleReservationDto';
export * from './ServiceModuleSummaryDto';
export * from './ServiceModuleUsageDto';
export * from './StorageAccessRequest';
export * from './UploadAccessDto';
export * from './UserDetailsDto';
