/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InitFileUploadRequest
 */
export interface InitFileUploadRequest {
    /**
     * 
     * @type {string}
     * @memberof InitFileUploadRequest
     */
    filename: string;
    /**
     * 
     * @type {number}
     * @memberof InitFileUploadRequest
     */
    sizeBytes: number;
}

export function InitFileUploadRequestFromJSON(json: any): InitFileUploadRequest {
    return InitFileUploadRequestFromJSONTyped(json, false);
}

export function InitFileUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitFileUploadRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        'sizeBytes': json['sizeBytes'],
    };
}

export function InitFileUploadRequestToJSON(value?: InitFileUploadRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'filename': value.filename,
        'sizeBytes': value.sizeBytes,
    };
}

