/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InitFileUploadResponse
 */
export interface InitFileUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof InitFileUploadResponse
     */
    provider: InitFileUploadResponseProviderEnum;
    /**
     * 
     * @type {string}
     * @memberof InitFileUploadResponse
     */
    filePath: string;
    /**
     * 
     * @type {string}
     * @memberof InitFileUploadResponse
     */
    uploadUrl: string;
    /**
     * 
     * @type {Date}
     * @memberof InitFileUploadResponse
     */
    validTo: Date;
    /**
     * 
     * @type {string}
     * @memberof InitFileUploadResponse
     */
    httpMethod: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof InitFileUploadResponse
     */
    headers: { [key: string]: string; };
}

/**
* @export
* @enum {string}
*/
export enum InitFileUploadResponseProviderEnum {
    Gcloud = 'GCLOUD'
}

export function InitFileUploadResponseFromJSON(json: any): InitFileUploadResponse {
    return InitFileUploadResponseFromJSONTyped(json, false);
}

export function InitFileUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitFileUploadResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'filePath': json['filePath'],
        'uploadUrl': json['uploadUrl'],
        'validTo': (new Date(json['validTo'])),
        'httpMethod': json['httpMethod'],
        'headers': json['headers'],
    };
}

export function InitFileUploadResponseToJSON(value?: InitFileUploadResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provider': value.provider,
        'filePath': value.filePath,
        'uploadUrl': value.uploadUrl,
        'validTo': (value.validTo.toISOString()),
        'httpMethod': value.httpMethod,
        'headers': value.headers,
    };
}

