/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstructionDto
 */
export interface InstructionDto {
    /**
     * 
     * @type {string}
     * @memberof InstructionDto
     */
    untrustedPossiblyDangerousHtml: string;
}

export function InstructionDtoFromJSON(json: any): InstructionDto {
    return InstructionDtoFromJSONTyped(json, false);
}

export function InstructionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstructionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'untrustedPossiblyDangerousHtml': json['untrustedPossiblyDangerousHtml'],
    };
}

export function InstructionDtoToJSON(value?: InstructionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'untrustedPossiblyDangerousHtml': value.untrustedPossiblyDangerousHtml,
    };
}

