/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinCourseRequest
 */
export interface JoinCourseRequest {
    /**
     * 
     * @type {string}
     * @memberof JoinCourseRequest
     */
    joinUUID: string;
    /**
     * 
     * @type {string}
     * @memberof JoinCourseRequest
     */
    password?: string;
}

export function JoinCourseRequestFromJSON(json: any): JoinCourseRequest {
    return JoinCourseRequestFromJSONTyped(json, false);
}

export function JoinCourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinCourseRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'joinUUID': json['joinUUID'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function JoinCourseRequestToJSON(value?: JoinCourseRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'joinUUID': value.joinUUID,
        'password': value.password,
    };
}

