/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FavouriteFileDto,
    FavouriteFileDtoFromJSON,
    FavouriteFileDtoFromJSONTyped,
    FavouriteFileDtoToJSON,
} from './FavouriteFileDto';

/**
 * 
 * @export
 * @interface MeDto
 */
export interface MeDto {
    /**
     * 
     * @type {string}
     * @memberof MeDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MeDto
     */
    surname: string;
    /**
     * 
     * @type {string}
     * @memberof MeDto
     */
    email: string;
    /**
     * 
     * @type {Array<FavouriteFileDto>}
     * @memberof MeDto
     */
    favouriteFiles: Array<FavouriteFileDto>;
}

export function MeDtoFromJSON(json: any): MeDto {
    return MeDtoFromJSONTyped(json, false);
}

export function MeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'surname': json['surname'],
        'email': json['email'],
        'favouriteFiles': ((json['favouriteFiles'] as Array<any>).map(FavouriteFileDtoFromJSON)),
    };
}

export function MeDtoToJSON(value?: MeDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'surname': value.surname,
        'email': value.email,
        'favouriteFiles': ((value.favouriteFiles as Array<any>).map(FavouriteFileDtoToJSON)),
    };
}

