/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModifyParticipantRequest
 */
export interface ModifyParticipantRequest {
    /**
     * 
     * @type {string}
     * @memberof ModifyParticipantRequest
     */
    email: string;
}

export function ModifyParticipantRequestFromJSON(json: any): ModifyParticipantRequest {
    return ModifyParticipantRequestFromJSONTyped(json, false);
}

export function ModifyParticipantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyParticipantRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ModifyParticipantRequestToJSON(value?: ModifyParticipantRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

