/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParameterDescription
 */
export interface ParameterDescription {
    /**
     * 
     * @type {string}
     * @memberof ParameterDescription
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ParameterDescription
     */
    required: boolean;
    /**
     * 
     * @type {string}
     * @memberof ParameterDescription
     */
    type: ParameterDescriptionTypeEnum;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ParameterDescription
     */
    translatedLabel?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof ParameterDescription
     */
    clientValidationHelpers?: { [key: string]: object; };
}

/**
* @export
* @enum {string}
*/
export enum ParameterDescriptionTypeEnum {
    File = 'FILE',
    Text = 'TEXT'
}

export function ParameterDescriptionFromJSON(json: any): ParameterDescription {
    return ParameterDescriptionFromJSONTyped(json, false);
}

export function ParameterDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParameterDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'required': json['required'],
        'type': json['type'],
        'translatedLabel': !exists(json, 'translatedLabel') ? undefined : json['translatedLabel'],
        'clientValidationHelpers': !exists(json, 'clientValidationHelpers') ? undefined : json['clientValidationHelpers'],
    };
}

export function ParameterDescriptionToJSON(value?: ParameterDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'required': value.required,
        'type': value.type,
        'translatedLabel': value.translatedLabel,
        'clientValidationHelpers': value.clientValidationHelpers,
    };
}

