/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDetailsDto,
    UserDetailsDtoFromJSON,
    UserDetailsDtoFromJSONTyped,
    UserDetailsDtoToJSON,
} from './UserDetailsDto';

/**
 * 
 * @export
 * @interface ParticipantDetailsDto
 */
export interface ParticipantDetailsDto {
    /**
     * 
     * @type {UserDetailsDto}
     * @memberof ParticipantDetailsDto
     */
    participant: UserDetailsDto;
    /**
     * 
     * @type {Date}
     * @memberof ParticipantDetailsDto
     */
    joinedAt: Date;
}

export function ParticipantDetailsDtoFromJSON(json: any): ParticipantDetailsDto {
    return ParticipantDetailsDtoFromJSONTyped(json, false);
}

export function ParticipantDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParticipantDetailsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'participant': UserDetailsDtoFromJSON(json['participant']),
        'joinedAt': (new Date(json['joinedAt'])),
    };
}

export function ParticipantDetailsDtoToJSON(value?: ParticipantDetailsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'participant': UserDetailsDtoToJSON(value.participant),
        'joinedAt': (value.joinedAt.toISOString()),
    };
}

