/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenDto
 */
export interface RefreshTokenDto {
    /**
     * 
     * @type {number}
     * @memberof RefreshTokenDto
     */
    tokenId: number;
    /**
     * 
     * @type {number}
     * @memberof RefreshTokenDto
     */
    expiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof RefreshTokenDto
     */
    refreshToken: string;
}

export function RefreshTokenDtoFromJSON(json: any): RefreshTokenDto {
    return RefreshTokenDtoFromJSONTyped(json, false);
}

export function RefreshTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenId': json['tokenId'],
        'expiresIn': json['expiresIn'],
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshTokenDtoToJSON(value?: RefreshTokenDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tokenId': value.tokenId,
        'expiresIn': value.expiresIn,
        'refreshToken': value.refreshToken,
    };
}

