/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoteFile
 */
export interface RemoteFile {
    /**
     * 
     * @type {number}
     * @memberof RemoteFile
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RemoteFile
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof RemoteFile
     */
    sizeBytes?: number;
    /**
     * 
     * @type {Date}
     * @memberof RemoteFile
     */
    createdAt?: Date;
}

export function RemoteFileFromJSON(json: any): RemoteFile {
    return RemoteFileFromJSONTyped(json, false);
}

export function RemoteFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoteFile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'sizeBytes': !exists(json, 'sizeBytes') ? undefined : json['sizeBytes'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function RemoteFileToJSON(value?: RemoteFile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'path': value.path,
        'sizeBytes': value.sizeBytes,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

