/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReserveServiceModuleRequest
 */
export interface ReserveServiceModuleRequest {
    /**
     * 
     * @type {string}
     * @memberof ReserveServiceModuleRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ReserveServiceModuleRequest
     */
    instructionsFromTechnicalTeacher: string;
    /**
     * 
     * @type {string}
     * @memberof ReserveServiceModuleRequest
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof ReserveServiceModuleRequest
     */
    scheduleTypeName: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ReserveServiceModuleRequest
     */
    dynamicProperties: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof ReserveServiceModuleRequest
     */
    isPublic: boolean;
}

export function ReserveServiceModuleRequestFromJSON(json: any): ReserveServiceModuleRequest {
    return ReserveServiceModuleRequestFromJSONTyped(json, false);
}

export function ReserveServiceModuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReserveServiceModuleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'instructionsFromTechnicalTeacher': json['instructionsFromTechnicalTeacher'],
        'subject': json['subject'],
        'scheduleTypeName': json['scheduleTypeName'],
        'dynamicProperties': json['dynamicProperties'],
        'isPublic': json['isPublic'],
    };
}

export function ReserveServiceModuleRequestToJSON(value?: ReserveServiceModuleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'instructionsFromTechnicalTeacher': value.instructionsFromTechnicalTeacher,
        'subject': value.subject,
        'scheduleTypeName': value.scheduleTypeName,
        'dynamicProperties': value.dynamicProperties,
        'isPublic': value.isPublic,
    };
}

