/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelectedServiceModuleDto
 */
export interface SelectedServiceModuleDto {
    /**
     * 
     * @type {number}
     * @memberof SelectedServiceModuleDto
     */
    serviceModuleId: number;
    /**
     * 
     * @type {boolean}
     * @memberof SelectedServiceModuleDto
     */
    linkConfirmationRequired: boolean;
}

export function SelectedServiceModuleDtoFromJSON(json: any): SelectedServiceModuleDto {
    return SelectedServiceModuleDtoFromJSONTyped(json, false);
}

export function SelectedServiceModuleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectedServiceModuleDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'serviceModuleId': json['serviceModuleId'],
        'linkConfirmationRequired': json['linkConfirmationRequired'],
    };
}

export function SelectedServiceModuleDtoToJSON(value?: SelectedServiceModuleDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'serviceModuleId': value.serviceModuleId,
        'linkConfirmationRequired': value.linkConfirmationRequired,
    };
}

