/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceConnectionDetailsDto
 */
export interface ServiceConnectionDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof ServiceConnectionDetailsDto
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceConnectionDetailsDto
     */
    serviceName: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceConnectionDetailsDto
     */
    connectionInstruction: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceConnectionDetailsDto
     */
    connectionInfo?: string;
}

export function ServiceConnectionDetailsDtoFromJSON(json: any): ServiceConnectionDetailsDto {
    return ServiceConnectionDetailsDtoFromJSONTyped(json, false);
}

export function ServiceConnectionDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceConnectionDetailsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'serviceName': json['serviceName'],
        'connectionInstruction': json['connectionInstruction'],
        'connectionInfo': !exists(json, 'connectionInfo') ? undefined : json['connectionInfo'],
    };
}

export function ServiceConnectionDetailsDtoToJSON(value?: ServiceConnectionDetailsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'serviceName': value.serviceName,
        'connectionInstruction': value.connectionInstruction,
        'connectionInfo': value.connectionInfo,
    };
}

