/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceModuleDetailsResp
 */
export interface ServiceModuleDetailsResp {
    /**
     * 
     * @type {number}
     * @memberof ServiceModuleDetailsResp
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceModuleDetailsResp
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModuleDetailsResp
     */
    instructionsFromTechnicalTeacher: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModuleDetailsResp
     */
    creatorName: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModuleDetailsResp
     */
    subject: string;
    /**
     * 
     * @type {Date}
     * @memberof ServiceModuleDetailsResp
     */
    creationTime: Date;
}

export function ServiceModuleDetailsRespFromJSON(json: any): ServiceModuleDetailsResp {
    return ServiceModuleDetailsRespFromJSONTyped(json, false);
}

export function ServiceModuleDetailsRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceModuleDetailsResp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'instructionsFromTechnicalTeacher': json['instructionsFromTechnicalTeacher'],
        'creatorName': json['creatorName'],
        'subject': json['subject'],
        'creationTime': (new Date(json['creationTime'])),
    };
}

export function ServiceModuleDetailsRespToJSON(value?: ServiceModuleDetailsResp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'instructionsFromTechnicalTeacher': value.instructionsFromTechnicalTeacher,
        'creatorName': value.creatorName,
        'subject': value.subject,
        'creationTime': (value.creationTime.toISOString()),
    };
}

