/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceModuleInstructionDto
 */
export interface ServiceModuleInstructionDto {
    /**
     * 
     * @type {string}
     * @memberof ServiceModuleInstructionDto
     */
    untrustedPossiblyDangerousHtml: string;
}

export function ServiceModuleInstructionDtoFromJSON(json: any): ServiceModuleInstructionDto {
    return ServiceModuleInstructionDtoFromJSONTyped(json, false);
}

export function ServiceModuleInstructionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceModuleInstructionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'untrustedPossiblyDangerousHtml': json['untrustedPossiblyDangerousHtml'],
    };
}

export function ServiceModuleInstructionDtoToJSON(value?: ServiceModuleInstructionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'untrustedPossiblyDangerousHtml': value.untrustedPossiblyDangerousHtml,
    };
}

