/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ParameterDescription,
    ParameterDescriptionFromJSON,
    ParameterDescriptionFromJSONTyped,
    ParameterDescriptionToJSON,
} from './ParameterDescription';

/**
 * 
 * @export
 * @interface ServiceConfigDto
 */
export interface ServiceConfigDto {
    /**
     * 
     * @type {string}
     * @memberof ServiceConfigDto
     */
    scheduleType: ServiceConfigDtoScheduleTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ServiceConfigDto
     */
    serviceName: string;
    /**
     * 
     * @type {Array<ParameterDescription>}
     * @memberof ServiceConfigDto
     */
    parameterDescriptions: Array<ParameterDescription>;
}

/**
* @export
* @enum {string}
*/
export enum ServiceConfigDtoScheduleTypeEnum {
    Jupyter = 'JUPYTER',
    Docker = 'DOCKER'
}

export function ServiceConfigDtoFromJSON(json: any): ServiceConfigDto {
    return ServiceConfigDtoFromJSONTyped(json, false);
}

export function ServiceConfigDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceConfigDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scheduleType': json['scheduleType'],
        'serviceName': json['serviceName'],
        'parameterDescriptions': ((json['parameterDescriptions'] as Array<any>).map(ParameterDescriptionFromJSON)),
    };
}

export function ServiceConfigDtoToJSON(value?: ServiceConfigDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scheduleType': value.scheduleType,
        'serviceName': value.serviceName,
        'parameterDescriptions': ((value.parameterDescriptions as Array<any>).map(ParameterDescriptionToJSON)),
    };
}

