/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDetailsDto,
    UserDetailsDtoFromJSON,
    UserDetailsDtoFromJSONTyped,
    UserDetailsDtoToJSON,
} from './UserDetailsDto';

/**
 * 
 * @export
 * @interface ServiceModuleSummaryDto
 */
export interface ServiceModuleSummaryDto {
    /**
     * 
     * @type {number}
     * @memberof ServiceModuleSummaryDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceModuleSummaryDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModuleSummaryDto
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModuleSummaryDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModuleSummaryDto
     */
    serviceName: string;
    /**
     * 
     * @type {UserDetailsDto}
     * @memberof ServiceModuleSummaryDto
     */
    creator: UserDetailsDto;
    /**
     * 
     * @type {Date}
     * @memberof ServiceModuleSummaryDto
     */
    createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof ServiceModuleSummaryDto
     */
    usedInActivitesCount: number;
}

export function ServiceModuleSummaryDtoFromJSON(json: any): ServiceModuleSummaryDto {
    return ServiceModuleSummaryDtoFromJSONTyped(json, false);
}

export function ServiceModuleSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceModuleSummaryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'subject': json['subject'],
        'description': json['description'],
        'serviceName': json['serviceName'],
        'creator': UserDetailsDtoFromJSON(json['creator']),
        'createdAt': (new Date(json['createdAt'])),
        'usedInActivitesCount': json['usedInActivitesCount'],
    };
}

export function ServiceModuleSummaryDtoToJSON(value?: ServiceModuleSummaryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'subject': value.subject,
        'description': value.description,
        'serviceName': value.serviceName,
        'creator': UserDetailsDtoToJSON(value.creator),
        'createdAt': (value.createdAt.toISOString()),
        'usedInActivitesCount': value.usedInActivitesCount,
    };
}

