/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface ServiceModule
 */
export interface ServiceModule {
    /**
     * 
     * @type {number}
     * @memberof ServiceModule
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    instructionsFromTechnicalTeacher?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    subject?: string;
    /**
     * 
     * @type {Date}
     * @memberof ServiceModule
     */
    creationTime?: Date;
    /**
     * 
     * @type {User}
     * @memberof ServiceModule
     */
    creator?: User;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    scheduleTypeName?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    scheduleTypeVersion?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ServiceModule
     */
    dynamicProperties?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof ServiceModule
     */
    isPublic?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceModule
     */
    isReady?: boolean;
}

export function ServiceModuleFromJSON(json: any): ServiceModule {
    return ServiceModuleFromJSONTyped(json, false);
}

export function ServiceModuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceModule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'instructionsFromTechnicalTeacher': !exists(json, 'instructionsFromTechnicalTeacher') ? undefined : json['instructionsFromTechnicalTeacher'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'creationTime': !exists(json, 'creationTime') ? undefined : (new Date(json['creationTime'])),
        'creator': !exists(json, 'creator') ? undefined : UserFromJSON(json['creator']),
        'scheduleTypeName': !exists(json, 'scheduleTypeName') ? undefined : json['scheduleTypeName'],
        'scheduleTypeVersion': !exists(json, 'scheduleTypeVersion') ? undefined : json['scheduleTypeVersion'],
        'dynamicProperties': !exists(json, 'dynamicProperties') ? undefined : json['dynamicProperties'],
        'isPublic': !exists(json, 'isPublic') ? undefined : json['isPublic'],
        'isReady': !exists(json, 'isReady') ? undefined : json['isReady'],
    };
}

export function ServiceModuleToJSON(value?: ServiceModule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'instructionsFromTechnicalTeacher': value.instructionsFromTechnicalTeacher,
        'subject': value.subject,
        'creationTime': value.creationTime === undefined ? undefined : (value.creationTime.toISOString()),
        'creator': UserToJSON(value.creator),
        'scheduleTypeName': value.scheduleTypeName,
        'scheduleTypeVersion': value.scheduleTypeVersion,
        'dynamicProperties': value.dynamicProperties,
        'isPublic': value.isPublic,
        'isReady': value.isReady,
    };
}

