/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SharedServiceModuleMdaDto,
    SharedServiceModuleMdaDtoFromJSON,
    SharedServiceModuleMdaDtoFromJSONTyped,
    SharedServiceModuleMdaDtoToJSON,
} from './SharedServiceModuleMdaDto';

/**
 * 
 * @export
 * @interface ServiceModuleMdaDto
 */
export interface ServiceModuleMdaDto {
    /**
     * 
     * @type {boolean}
     * @memberof ServiceModuleMdaDto
     */
    isIsolated: boolean;
    /**
     * 
     * @type {number}
     * @memberof ServiceModuleMdaDto
     */
    baseVcpu: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceModuleMdaDto
     */
    baseRam: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceModuleMdaDto
     */
    baseDisk: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceModuleMdaDto
     */
    baseBandwidth: number;
    /**
     * 
     * @type {SharedServiceModuleMdaDto}
     * @memberof ServiceModuleMdaDto
     */
    sharedServiceModuleMdaDto?: SharedServiceModuleMdaDto;
}

export function ServiceModuleMdaDtoFromJSON(json: any): ServiceModuleMdaDto {
    return ServiceModuleMdaDtoFromJSONTyped(json, false);
}

export function ServiceModuleMdaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceModuleMdaDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isIsolated': json['isIsolated'],
        'baseVcpu': json['baseVcpu'],
        'baseRam': json['baseRam'],
        'baseDisk': json['baseDisk'],
        'baseBandwidth': json['baseBandwidth'],
        'sharedServiceModuleMdaDto': !exists(json, 'sharedServiceModuleMdaDto') ? undefined : SharedServiceModuleMdaDtoFromJSON(json['sharedServiceModuleMdaDto']),
    };
}

export function ServiceModuleMdaDtoToJSON(value?: ServiceModuleMdaDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isIsolated': value.isIsolated,
        'baseVcpu': value.baseVcpu,
        'baseRam': value.baseRam,
        'baseDisk': value.baseDisk,
        'baseBandwidth': value.baseBandwidth,
        'sharedServiceModuleMdaDto': SharedServiceModuleMdaDtoToJSON(value.sharedServiceModuleMdaDto),
    };
}

