/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceModule
 */
export interface ServiceModule {
    /**
     * 
     * @type {number}
     * @memberof ServiceModule
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    instructionsFromTechnicalTeacher?: string;
}

export function ServiceModuleFromJSON(json: any): ServiceModule {
    return ServiceModuleFromJSONTyped(json, false);
}

export function ServiceModuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceModule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'instructionsFromTechnicalTeacher': !exists(json, 'instructionsFromTechnicalTeacher') ? undefined : json['instructionsFromTechnicalTeacher'],
    };
}

export function ServiceModuleToJSON(value?: ServiceModule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'instructionsFromTechnicalTeacher': value.instructionsFromTechnicalTeacher,
    };
}

