/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDetailsDto,
    UserDetailsDtoFromJSON,
    UserDetailsDtoFromJSONTyped,
    UserDetailsDtoToJSON,
} from './UserDetailsDto';

/**
 * 
 * @export
 * @interface ServiceModuleUsageDto
 */
export interface ServiceModuleUsageDto {
    /**
     * 
     * @type {UserDetailsDto}
     * @memberof ServiceModuleUsageDto
     */
    courseCreator: UserDetailsDto;
    /**
     * 
     * @type {number}
     * @memberof ServiceModuleUsageDto
     */
    courseId: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceModuleUsageDto
     */
    courseName: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModuleUsageDto
     */
    activityName: string;
    /**
     * 
     * @type {Date}
     * @memberof ServiceModuleUsageDto
     */
    addedAt: Date;
}

export function ServiceModuleUsageDtoFromJSON(json: any): ServiceModuleUsageDto {
    return ServiceModuleUsageDtoFromJSONTyped(json, false);
}

export function ServiceModuleUsageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceModuleUsageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'courseCreator': UserDetailsDtoFromJSON(json['courseCreator']),
        'courseId': json['courseId'],
        'courseName': json['courseName'],
        'activityName': json['activityName'],
        'addedAt': (new Date(json['addedAt'])),
    };
}

export function ServiceModuleUsageDtoToJSON(value?: ServiceModuleUsageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'courseCreator': UserDetailsDtoToJSON(value.courseCreator),
        'courseId': value.courseId,
        'courseName': value.courseName,
        'activityName': value.activityName,
        'addedAt': (value.addedAt.toISOString()),
    };
}

