/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceModule
 */
export interface ServiceModule {
    /**
     * 
     * @type {number}
     * @memberof ServiceModule
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    instructionsFromTechnicalTeacher?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    creatorName?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceModule
     */
    scheduleType?: ServiceModuleScheduleTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof ServiceModule
     */
    creationTime?: Date;
}

/**
* @export
* @enum {string}
*/
export enum ServiceModuleScheduleTypeEnum {
    Jupyter = 'JUPYTER',
    Docker = 'DOCKER'
}

export function ServiceModuleFromJSON(json: any): ServiceModule {
    return ServiceModuleFromJSONTyped(json, false);
}

export function ServiceModuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceModule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'instructionsFromTechnicalTeacher': !exists(json, 'instructionsFromTechnicalTeacher') ? undefined : json['instructionsFromTechnicalTeacher'],
        'creatorName': !exists(json, 'creatorName') ? undefined : json['creatorName'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'scheduleType': !exists(json, 'scheduleType') ? undefined : json['scheduleType'],
        'creationTime': !exists(json, 'creationTime') ? undefined : (new Date(json['creationTime'])),
    };
}

export function ServiceModuleToJSON(value?: ServiceModule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'instructionsFromTechnicalTeacher': value.instructionsFromTechnicalTeacher,
        'creatorName': value.creatorName,
        'subject': value.subject,
        'scheduleType': value.scheduleType,
        'creationTime': value.creationTime === undefined ? undefined : (value.creationTime.toISOString()),
    };
}

