/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InstructionDto,
    InstructionDtoFromJSON,
    InstructionDtoFromJSONTyped,
    InstructionDtoToJSON,
} from './InstructionDto';

/**
 * 
 * @export
 * @interface ServiceConnectionDetailsDto
 */
export interface ServiceConnectionDetailsDto {
    /**
     * 
     * @type {{ [key: string]: InstructionDto; }}
     * @memberof ServiceConnectionDetailsDto
     */
    connectionInstructions: { [key: string]: InstructionDto; };
    /**
     * 
     * @type {string}
     * @memberof ServiceConnectionDetailsDto
     */
    url: string;
}

export function ServiceConnectionDetailsDtoFromJSON(json: any): ServiceConnectionDetailsDto {
    return ServiceConnectionDetailsDtoFromJSONTyped(json, false);
}

export function ServiceConnectionDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceConnectionDetailsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'connectionInstructions': (mapValues(json['connectionInstructions'], InstructionDtoFromJSON)),
        'url': json['url'],
    };
}

export function ServiceConnectionDetailsDtoToJSON(value?: ServiceConnectionDetailsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'connectionInstructions': (mapValues(value.connectionInstructions, InstructionDtoToJSON)),
        'url': value.url,
    };
}

