/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SharedServiceModuleMdaDto
 */
export interface SharedServiceModuleMdaDto {
    /**
     * 
     * @type {number}
     * @memberof SharedServiceModuleMdaDto
     */
    usersPerAdditionalCore: number;
    /**
     * 
     * @type {number}
     * @memberof SharedServiceModuleMdaDto
     */
    usersPerAdditionalRamGb: number;
    /**
     * 
     * @type {number}
     * @memberof SharedServiceModuleMdaDto
     */
    usersPerAdditionalDiskGb: number;
    /**
     * 
     * @type {number}
     * @memberof SharedServiceModuleMdaDto
     */
    usersPerAdditionalBandwidthGbps: number;
}

export function SharedServiceModuleMdaDtoFromJSON(json: any): SharedServiceModuleMdaDto {
    return SharedServiceModuleMdaDtoFromJSONTyped(json, false);
}

export function SharedServiceModuleMdaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedServiceModuleMdaDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'usersPerAdditionalCore': json['usersPerAdditionalCore'],
        'usersPerAdditionalRamGb': json['usersPerAdditionalRamGb'],
        'usersPerAdditionalDiskGb': json['usersPerAdditionalDiskGb'],
        'usersPerAdditionalBandwidthGbps': json['usersPerAdditionalBandwidthGbps'],
    };
}

export function SharedServiceModuleMdaDtoToJSON(value?: SharedServiceModuleMdaDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'usersPerAdditionalCore': value.usersPerAdditionalCore,
        'usersPerAdditionalRamGb': value.usersPerAdditionalRamGb,
        'usersPerAdditionalDiskGb': value.usersPerAdditionalDiskGb,
        'usersPerAdditionalBandwidthGbps': value.usersPerAdditionalBandwidthGbps,
    };
}

