/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ActivityFilesDto,
    ActivityFilesDtoFromJSON,
    ActivityFilesDtoFromJSONTyped,
    ActivityFilesDtoToJSON,
} from './ActivityFilesDto';
import {
    UserDetailsDto,
    UserDetailsDtoFromJSON,
    UserDetailsDtoFromJSONTyped,
    UserDetailsDtoToJSON,
} from './UserDetailsDto';

/**
 * 
 * @export
 * @interface TeacherActivityFilesDto
 */
export interface TeacherActivityFilesDto {
    /**
     * 
     * @type {{ [key: string]: ActivityFilesDto; }}
     * @memberof TeacherActivityFilesDto
     */
    userIdToUserFiles: { [key: string]: ActivityFilesDto; };
    /**
     * 
     * @type {{ [key: string]: UserDetailsDto; }}
     * @memberof TeacherActivityFilesDto
     */
    userIdToUserDetails: { [key: string]: UserDetailsDto; };
}

export function TeacherActivityFilesDtoFromJSON(json: any): TeacherActivityFilesDto {
    return TeacherActivityFilesDtoFromJSONTyped(json, false);
}

export function TeacherActivityFilesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeacherActivityFilesDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userIdToUserFiles': (mapValues(json['userIdToUserFiles'], ActivityFilesDtoFromJSON)),
        'userIdToUserDetails': (mapValues(json['userIdToUserDetails'], UserDetailsDtoFromJSON)),
    };
}

export function TeacherActivityFilesDtoToJSON(value?: TeacherActivityFilesDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userIdToUserFiles': (mapValues(value.userIdToUserFiles, ActivityFilesDtoToJSON)),
        'userIdToUserDetails': (mapValues(value.userIdToUserDetails, UserDetailsDtoToJSON)),
    };
}

