/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InitFileUploadRequest,
    InitFileUploadRequestFromJSON,
    InitFileUploadRequestFromJSONTyped,
    InitFileUploadRequestToJSON,
} from './InitFileUploadRequest';
import {
    StorageAccessRequest,
    StorageAccessRequestFromJSON,
    StorageAccessRequestFromJSONTyped,
    StorageAccessRequestToJSON,
} from './StorageAccessRequest';

/**
 * 
 * @export
 * @interface UploadAccessDto
 */
export interface UploadAccessDto {
    /**
     * 
     * @type {InitFileUploadRequest}
     * @memberof UploadAccessDto
     */
    initFileUploadRequest: InitFileUploadRequest;
    /**
     * 
     * @type {StorageAccessRequest}
     * @memberof UploadAccessDto
     */
    storageAccessRequest: StorageAccessRequest;
}

export function UploadAccessDtoFromJSON(json: any): UploadAccessDto {
    return UploadAccessDtoFromJSONTyped(json, false);
}

export function UploadAccessDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadAccessDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'initFileUploadRequest': InitFileUploadRequestFromJSON(json['initFileUploadRequest']),
        'storageAccessRequest': StorageAccessRequestFromJSON(json['storageAccessRequest']),
    };
}

export function UploadAccessDtoToJSON(value?: UploadAccessDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'initFileUploadRequest': InitFileUploadRequestToJSON(value.initFileUploadRequest),
        'storageAccessRequest': StorageAccessRequestToJSON(value.storageAccessRequest),
    };
}

