/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCourseId
 */
export interface UserCourseId {
    /**
     * 
     * @type {number}
     * @memberof UserCourseId
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof UserCourseId
     */
    courseId?: number;
}

export function UserCourseIdFromJSON(json: any): UserCourseId {
    return UserCourseIdFromJSONTyped(json, false);
}

export function UserCourseIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCourseId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'courseId': !exists(json, 'courseId') ? undefined : json['courseId'],
    };
}

export function UserCourseIdToJSON(value?: UserCourseId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'courseId': value.courseId,
    };
}

