/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDetailsDto
 */
export interface UserDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof UserDetailsDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailsDto
     */
    surname: string;
    /**
     * 
     * @type {string}
     * @memberof UserDetailsDto
     */
    email: string;
}

export function UserDetailsDtoFromJSON(json: any): UserDetailsDto {
    return UserDetailsDtoFromJSONTyped(json, false);
}

export function UserDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetailsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'surname': json['surname'],
        'email': json['email'],
    };
}

export function UserDetailsDtoToJSON(value?: UserDetailsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'surname': value.surname,
        'email': value.email,
    };
}

