/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VmDto
 */
export interface VmDto {
    /**
     * 
     * @type {number}
     * @memberof VmDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof VmDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof VmDto
     */
    vcpu: number;
    /**
     * 
     * @type {number}
     * @memberof VmDto
     */
    ramGB: number;
    /**
     * 
     * @type {number}
     * @memberof VmDto
     */
    bandwidthMbps: number;
    /**
     * 
     * @type {string}
     * @memberof VmDto
     */
    descriptionHtml: string;
}

export function VmDtoFromJSON(json: any): VmDto {
    return VmDtoFromJSONTyped(json, false);
}

export function VmDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VmDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'vcpu': json['vcpu'],
        'ramGB': json['ramGB'],
        'bandwidthMbps': json['bandwidthMbps'],
        'descriptionHtml': json['descriptionHtml'],
    };
}

export function VmDtoToJSON(value?: VmDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'vcpu': value.vcpu,
        'ramGB': value.ramGB,
        'bandwidthMbps': value.bandwidthMbps,
        'descriptionHtml': value.descriptionHtml,
    };
}

